<template>
  

   <div class="wrapper" ref="aaa">
     <ul class="content">
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
     <li>分类列表</li>
   </ul>
   </div>
  
</template>

<script>

import BScroll from 'better-scroll'
export default {
  name: 'Category',
  data(){
    return {
      scroll:null
    }
  },
  created(){
    // 在这里拿不到数据只能在挂载后拿到数据



    //  console.log(document.querySelector('.wrapper'));
    // console.log(this.$refs.aaa);
    // this.scroll = new BScroll(document.querySelector('.wrapper'),{

    // })
  },
  // 挂载后
  mounted(){
    // console.log(document.querySelector('.wrapper'));
    // console.log(this.$refs.aaa);
    this.scroll = new BScroll(document.querySelector('.wrapper'),{
     probeType:3,
     pullUpLoad:true
    })
    this.scroll.on('scroll',(position)=>{
      // console.log(position);
    })
    this.scroll.on('pullingUp',()=>{
      console.log('上拉加载更多....');
// 上面的代码只能上拉加载一次
// 加上下面一句代码可以加载更多的数据
      this.scroll.finishPullUp()
    })
  }
 
}
</script>

<style scoped>
.wrapper{
  height: 150px;
  background-color: red;

 /* 可以使滑动时跟丝滑  当不建议用原生 */
  overflow: hidden;
  /* overflow-y: scroll; */
}
</style>>
 
  



